//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Casgem_Portfolio.Models.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CasgemPortfolioEntities1 : DbContext
    {
        public CasgemPortfolioEntities1()
            : base("name=CasgemPortfolioEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_feature> tbl_feature { get; set; }
        public virtual DbSet<tbl_message> tbl_message { get; set; }
        public virtual DbSet<tbl_service> tbl_service { get; set; }
        public virtual DbSet<tbl_referance> tbl_referance { get; set; }
        public virtual DbSet<tbl_projects> tbl_projects { get; set; }
        public virtual DbSet<tbl_resume> tbl_resume { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TblDepartment> TblDepartment { get; set; }
        public virtual DbSet<TblEmployee> TblEmployee { get; set; }
    }
}
