//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Casgem_Portfolio.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblContact
    {
        public int ContactID { get; set; }
        public string SenderEmail { get; set; }
        public string Subject { get; set; }
        public string Content_ { get; set; }
        public string Message { get; set; }
    }
}
